function checkLogin() {
  var cookie = document.cookie; // Get the cookie string
  if (cookie.includes("login=true")) { // Check if the cookie contains "login=true"
    console.log("success"); // Log success if the cookie exists
  } else {
    window.location.href = "/marshalling/login"; // Redirect to login page if the cookie doesn't exist
  }
}

function registerCompetitor() {

}

function studentsRegistered() {

}

function studentReport() {
  
}

function logout() {
  document.cookie = "login=false; expires=" + expires.toUTCString() + "; path=/"; // Saves (very basic) login cookie to the browser
  window.location.href = "/marshalling/login"; // Redirects back to login page
}

// NOTE 30/05/23 12:43pm - Attempting to use GitHub Copilot here
// NOTE 30/05/23 4:47pm - GitHub Copilot is not very good at JavaScript (that message was generated by github copilot)
// NOTE 31/05/23 9:30am - i did it :)
// NOTE 31/05/23 12:28pm - no i didnt :(
// NOTE 31/05/23 1:35pm - yes i did :)