function checkLogin() {
  var cookie = document.cookie; // Get the cookie string
  if (!cookie.includes("login=true")) { // Check if the cookie does not contain "login=true"
    window.location.href = "/marshalling/login"; // Redirect to login page if the cookie doesn't exist
  }
}

function registerCompetitor() { 

}

function studentsRegistered() { // Function that displays all students registered for the competition

}

function studentReport() { 

}

function logoutFlow() {
  document.cookie = "login=false;" + "; path=/"; // Saves (very basic) login cookie to the browser
  window.location.href = "/marshalling/login"; // Redirects back to login page
}

// NOTE 30/05/23 12:43pm - Attempting to use GitHub Copilot here
// NOTE 30/05/23 4:47pm - GitHub Copilot is not very good at JavaScript (that message was generated by github copilot)