function checkLogin() {
  var cookie = document.cookie; // Sets var "cookie" to the value of the cookie in the browser
  if (cookie.includes("login=true")) { // Checks if the cookie contains the string "login=true"
    window.location.href = "https://athleticscarnival.flareon.lol/marshallpage"; // Continues to marshalling page if cookie exists
  } else {
    window.location.href = "https://athleticscarnival.flareon.lol/login"; // Redirects to login page if valid cookie does not exist
  }
}

// NOTE 30/05/23 12:43pm - Attempting to use GitHub Copilot here
// NOTE 30/05/23 4:47pm - GitHub Copilot is not very good at JavaScript (that message was generated by github copilot)
// NOTE 31/05/23 9:30am - i did it :)