// Function that gets cookie from browser (login=true) and loads marshallpage index.html if exists. Otherwise, redirect to login page. 
function checkLogin() {
  var cookie = document.cookie;
  if (cookie.includes("login=true")) {
    window.location.href = "https://athleticscarnival.flareon.lol/marshallpage";
  } else {
    window.location.href = "https://athleticscarnival.flareon.lol/login";
  }
}

// NOTE 30/05/23 12:43pm - Attempting to use GitHub Copilot here
// NOTE 30/05/23 4:47pm - GitHub Copilot is not very good at JavaScript (that message was generated by github copilot)